name: Version check
on:
  workflow_dispatch:
  schedule:
    - cron:  '17,47 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [nightly]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        token: ${{ secrets.PERSONAL_TOKEN }}
    - id: latestrelease
      name: Get Latest Release
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        repository: danimart1991/Sonarr
    - name: Echo Latest Release
      run: echo 'Latest Release is:' ${{ steps.latestrelease.outputs.release }}
    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: '.VERSION'
        FILE_DATA: ${{ steps.latestrelease.outputs.release }}
    - name: Commit and push changes
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4.9.1
      with:
        commit_message: ${{ format('Updated to version - {0}', steps.latestrelease.outputs.release) }}
        branch: ${{ matrix.branch }}
